export const books = [
    {
        id: '1',
        name: 'Сліпий убивця',
        img: 'https://uabooks.net/posters/487.jpg',
        author: 'Марґарет Етвуд',
        popular: true,
    },
    {
        id: '2',
        name: 'Дорога',
        img: 'https://uabooks.net/posters/522.jpg',
        author: 'Кормак МакКарті',
        popular: true,
    },
    {
        id: '3',
        name: 'Задзеркалля',
        img: 'https://uabooks.net/posters/521.jpg',
        author: 'Керол Джонстоун',
        required: true,
    },
    {
        id: '4',
        name: 'Піранезі',
        img: 'https://uabooks.net/posters/520.jpg',
        author: 'Сюзанна Кларк',
        required: true,
    },
    {
        id: '5',
        name: 'Джонатан Стрейндж і м-р Норрелл',
        img: 'https://uabooks.net/posters/519.jpg',
        author: 'Сюзанна Кларк',
        popular: true,
    },
    {
        id: '6',
        name: 'Брама Птолемея',
        img: 'https://uabooks.net/posters/518.jpg',
        author: 'Джонатан Страуд',
    },
    {
        id: '7',
        name: 'Нестерпна легкість буття',
        img: 'https://uabooks.net/posters/514.jpg',
        author: 'Мілан Кундера',
        required: true,
    },
    {
        id: '8',
        name: 'Вальс на прощання',
        img: 'https://uabooks.net/posters/513.jpg',
        author: 'Мілан Кундера',
    },
    {
        id: '9',
        name: 'Незнайомка з Вілдфел-Холу',
        img: 'https://uabooks.net/posters/512.jpg',
        author: 'Анна Бронте',
    },
    {
        id: '10',
        name: 'Одного разу на Різдво',
        img: 'https://uabooks.net/posters/511.jpg',
        author: 'Джозі Сільвер',
        required: true,
    },
    {
        id: '11',
        name: 'Записано на кістках. Друге розслідування',
        img: 'https://uabooks.net/posters/510.jpg',
        author: 'Саймон Бекетт',
        required: true,
    },
    {
        id: '12',
        name: 'Хімія смерті. Перше розслідування',
        img: 'https://uabooks.net/posters/509.jpg',
        author: 'Саймон Бекетт',
    },
    {
        id: '13',
        name: 'Учитель',
        img: 'https://uabooks.net/posters/508.jpg',
        author: 'Шарлотта Бронте',
    },
    {
        id: '14',
        name: 'Джейн Ейр',
        img: 'https://uabooks.net/posters/507.jpg',
        author: 'Шарлотта Бронте',
    },
    {
        id: '15',
        name: 'Танок драконів',
        img: 'https://uabooks.net/posters/506.jpg',
        author: 'Джордж Мартін',
    },
    {
        id: '16',
        name: 'Буря мечів',
        img: 'https://uabooks.net/posters/504.jpg',
        author: 'Джордж Мартін',
    },
    {
        id: '17',
        name: 'Друге життя Брі Таннер',
        img: 'https://uabooks.net/posters/501.jpg',
        author: 'Стефані Маєр',
    },
    {
        id: '18',
        name: 'Посуха',
        img: 'https://uabooks.net/posters/494.jpg',
        author: 'Джейн Гарпер',
        popular: true,
    },
    {
        id: '19',
        name: 'Лист до короля',
        img: 'https://uabooks.net/posters/493.jpg',
        author: 'Тонке Драгт',
        popular: true,
    },
    {
        id: '20',
        name: 'Той, хто вбиває',
        img: 'https://uabooks.net/posters/492.jpg',
        author: 'Кріс Тведт',
    },
];
